# Data Preprocessing
- Importing Libraries<br>
- Importing Data<br>
- Train-test split<br>
- Imputing Missing Data<br>
- Encoding Categorical Data<br>
- Feature Scaling<br>

<h2>Importing Libraries</h2>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("./Data/50_Startups.csv")

In [20]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(type(X))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>

In [15]:
#Taking features and matrix and target as vector
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(type(X))
print(type(y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

<h2>Importing Data</h2>

<h2>Imputing Missing Data</h2>

<h2>Encoding Categorical Data</h2>

- Encoding categorical Features
- Encoding categorical Target

In [21]:
#X.head()
X

    R&D Spend  Administration  Marketing Spend       State
0   165349.20       136897.80        471784.10    New York
1   162597.70       151377.59        443898.53  California
2   153441.51       101145.55        407934.54     Florida
3   144372.41       118671.85        383199.62    New York
4   142107.34        91391.77        366168.42     Florida
5   131876.90        99814.71        362861.36    New York
6   134615.46       147198.87        127716.82  California
7   130298.13       145530.06        323876.68     Florida
8   120542.52       148718.95        311613.29    New York
9   123334.88       108679.17        304981.62  California
10  101913.08       110594.11        229160.95     Florida
11  100671.96        91790.61        249744.55  California
12   93863.75       127320.38        249839.44     Florida
13   91992.39       135495.07        252664.93  California
14  119943.24       156547.42        256512.92     Florida
15  114523.61       122616.84        261776.23    New York
16   78013.11       121597.55        264346.06  California
17   94657.16       145077.58        282574.31    New York
18   91749.16       114175.79        294919.57     Florida
19   86419.70       153514.11             0.00    New York
20   76253.86       113867.30        298664.47  California
21   78389.47       153773.43        299737.29    New York
22   73994.56       122782.75        303319.26     Florida
23   67532.53       105751.03        304768.73     Florida
24   77044.01        99281.34        140574.81    New York
25   64664.71       139553.16        137962.62  California
26   75328.87       144135.98        134050.07     Florida
27   72107.60       127864.55        353183.81    New York
28   66051.52       182645.56        118148.20     Florida
29   65605.48       153032.06        107138.38    New York
30   61994.48       115641.28         91131.24     Florida
31   61136.38       152701.92         88218.23    New York
32   63408.86       129219.61         46085.25  California
33   55493.95       103057.49        214634.81     Florida
34   46426.07       157693.92        210797.67  California
35   46014.02        85047.44        205517.64    New York
36   28663.76       127056.21        201126.82     Florida
37   44069.95        51283.14        197029.42  California
38   20229.59        65947.93        185265.10    New York
39   38558.51        82982.09        174999.30  California
40   28754.33       118546.05        172795.67  California
41   27892.92        84710.77        164470.71     Florida
42   23640.93        96189.63        148001.11  California
43   15505.73       127382.30         35534.17    New York
44   22177.74       154806.14         28334.72  California
45    1000.23       124153.04          1903.93    New York
46    1315.46       115816.21        297114.46     Florida
47       0.00       135426.92             0.00  California
48     542.05        51743.15             0.00    New York
49       0.00       116983.80         45173.06  California

In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
OH_encoder = OneHotEncoder(drop='first',sparse=False)
ct = ColumnTransformer(transformers = [('encoder', OH_encoder, [3])], remainder='passthrough')
X_OH = np.array(ct.fit_transform(X.values))
X_OH

array([[0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 1.0, 94657.16, 145077.58, 282574.31],
       [1.0, 0.0, 91749.16, 114175.79, 294919.57],
       [0.0, 1.0, 86419.7, 153514.11, 0.0],
       [0.0, 0.0, 76253.86, 113867.3, 298664.47],
       [0.0, 1.0, 78389.47, 153773.43, 299737.29],
       [1.0, 0.0, 73994.56, 122782.75, 303319.26],
       [1.0, 0.0, 67532.53, 105751.03, 304768.73],
       [0.0, 1.0, 77044.01, 99281.34, 140574.81],
       [0.0, 0.0, 64664.71, 139553.16, 137962.62],
       [1.0, 0.0, 75328.87, 144135.98, 134050.07],
       [0.0, 1.0, 72107.6, 127864.55, 353183.81],
       [1.0, 0.0, 66051.52, 182645.56, 118148.2],
       [0.0, 1.0, 65605.48, 153032.06, 107138.38],
       [1.0, 0.0, 61994.48, 115641.28, 91131.24],
       [0.0, 1.0, 61136.38, 152701.92, 88218.23],
       [0.0, 0.0, 63408.86, 129219.61, 46085.25],
       [1.0, 0.0, 55493.95, 103057.49, 214634.81],
       [0.0, 0.0, 46426.07, 157693.92, 210797.67],
       [0.0, 1.0, 46014.02, 85047.44, 205517.64],
       [1.0, 0.0, 28663.76, 127056.21, 201126.82],
       [0.0, 0.0, 44069.95, 51283.14, 197029.42],
       [0.0, 1.0, 20229.59, 65947.93, 185265.1],
       [0.0, 0.0, 38558.51, 82982.09, 174999.3],
       [0.0, 0.0, 28754.33, 118546.05, 172795.67],
       [1.0, 0.0, 27892.92, 84710.77, 164470.71],
       [0.0, 0.0, 23640.93, 96189.63, 148001.11],
       [0.0, 1.0, 15505.73, 127382.3, 35534.17],
       [0.0, 0.0, 22177.74, 154806.14, 28334.72],
       [0.0, 1.0, 1000.23, 124153.04, 1903.93],
       [1.0, 0.0, 1315.46, 115816.21, 297114.46],
       [0.0, 0.0, 0.0, 135426.92, 0.0],
       [0.0, 1.0, 542.05, 51743.15, 0.0],
       [0.0, 0.0, 0.0, 116983.8, 45173.06]], dtype=object)

<h2>Feature Scaling</h2>

- Normalization
- Standardization

**Q - Should feature scaling be applied on dummy variables?**